apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xr74bshfa-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xr74bshfa-nodejs 
  name: xr74bshfa-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: xr74bshfa-nodejs 
