apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xr74bshfa-nodejs 
  janus-idp.io/tekton: xr74bshfa-nodejs
  backstage.io/kubernetes-id: xr74bshfa-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xr74bshfa-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml